apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  type: NodePort
  ports:
  - name: "db-service"
    port: 27017
    targetPort: 27017
    nodePort: 30000
  selector:
    app: db
  