apiVersion: v1
kind: Service
metadata:
  name: front-end-react
spec:
  type: NodePort
  selector:
    app: front-end-react
  ports:
  - name: "front-end-react"
    port: 80
    targetPort: 80
    nodePort: 31002