name: Docker image build and push

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: front-end-react
            image_name: nuroz123/front-end-react
          - context: order-service
            image_name: nuroz123/order-service
          - context: user-service
            image_name: nuroz123/user-service

    steps:
      -
        name: List directories
        run: ls -l
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.context }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.context }}
          push: true
          tags: ${{ matrix.image_name }}:latest
